/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Johana-PS (https://sketchfab.com/Johana-PS)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cake-3d-756da5ef6d0249479510e6bdd1856e42
Title: Cake 3D
*/

import React, { ComponentPropsWithRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Cake1(
  props: Omit<ComponentPropsWithRef<'primitive'>, 'object'>,
) {
  const { scene } = useGLTF('/static/3js/cake/cake_3d.glb')
  return (
    <primitive
      object={scene}
      {...props}
      scale={[0.4, 0.4, 0.4]}
      rotation={[0, Math.PI * 1.5, 0]}
    />
  )
}

useGLTF.preload('/static/3js/cake/cake_3d.glb')
