/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Johana-PS (https://sketchfab.com/Johana-PS)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cake-3d-756da5ef6d0249479510e6bdd1856e42
Title: Cake 3D
*/

import React, { ComponentPropsWithRef, useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { Group } from 'three'

import gsap from 'gsap'
import { useGSAP } from '@gsap/react'

const ANIMATION: Record<
  'position' | 'scale' | 'rotation',
  { from: gsap.TweenVars; to: gsap.TweenVars }
> = {
  position: {
    from: {
      x: 0,
      y: 2,
      z: 0,
    },
    to: {
      x: 0,
      y: -2,
      z: 0,
    },
  },
  scale: {
    from: {
      x: 0.02,
      y: 0.02,
      z: 0.02,
    },
    to: {
      x: 0.4,
      y: 0.4,
      z: 0.4,
    },
  },
  rotation: {
    from: {
      x: 0,
      y: 0,
      z: 0,
    },
    to: {
      x: 0,
      y: Math.PI * 1.5,
      z: 0,
    },
  },
} as const

export function Cake1(props: ComponentPropsWithRef<'group'>) {
  const { scene } = useGLTF('/static/3js/cake/cake_3d.glb')
  const container = useRef<Group>(null)

  useGSAP(
    () => {
      if (!container.current) {
        return
      }
      gsap.fromTo(container.current.rotation, ANIMATION.rotation.from, {
        ...ANIMATION.rotation.to,
        duration: 1,
        ease: 'circ.out',
      })
      gsap.fromTo(container.current.scale, ANIMATION.scale.from, {
        ...ANIMATION.scale.to,
        duration: 1,
        ease: 'steps.out',
      })
      gsap.fromTo(container.current.position, ANIMATION.position.from, {
        ...ANIMATION.position.to,
        duration: 1,
        ease: 'bounce.out',
        delay: 0.2,
      })
    },
    { scope: container },
  )

  return (
    <group ref={container} {...props}>
      <primitive className="cake" object={scene} position={[0, 4.7, 0]} />
      <mesh rotation={[-Math.PI / 2, 0, 0]}>
        <planeGeometry args={[10, 10]} />
        <meshStandardMaterial color="#ffffff" />
      </mesh>
    </group>
  )
}

useGLTF.preload('/static/3js/cake/cake_3d.glb')
