packages:
  # Turbo only accepts * globs not ** globs
  - 'apps/hsp/*'
  - 'apps/learn/threejs/*'
  - 'apps/*'
  - 'packages/configs/*'
  - 'packages/*'
  - 'packages/hsp/*'
catalogs:
  # Pin the versions of the packages in the workspace
  base:
    '@types/node': 22.13.17
  prisma:
    prisma: 6.13.0
    '@prisma/client': 6.13.0
  gui:
    react: 19.2.0
    react-dom: 19.2.0
    react-icons: 5.5.0
    'eslint-plugin-react': '^7.37.5'
    'eslint-plugin-react-hooks': 7.0.1
    '@types/mdx': '2.0.13'
    '@types/react': 19.2.2
    '@types/react-dom': 19.2.2
    '@mdx-js/loader': '3.1.1'
    '@mdx-js/react': '3.1.1'
    '@next/mdx': '15.5.4'
    next: 16.0.3
    'sharp': '^0.34.4'
    '@next/eslint-plugin-next': 16.0.0
    next-themes: 0.4.6
    radix-ui: 1.4.3
  three:
    '@react-three/cannon': '6.6.0'
    '@react-three/drei': '10.7.6'
    '@react-three/fiber': '9.4.0'
    r3f-perf: 7.2.3
    'three': '^0.177.0'
    '@types/three': '^0.177.0'
    lil-gui: '0.20.0'
  markdown:
    # Content Collections (to manage markdown content)
    '@content-collections/core': '^0.11.1'
    '@content-collections/mdx': '^0.2.2' ## Markdown support
    '@content-collections/next': '^0.2.7' ## Next.js integration
    # Markdown processing
    'remark-gfm': '^4.0.1' # GitHub Flavored Markdown (tables, task lists, etc)
    'rehype-autolink-headings': '^7.1.0' # Adds links to headings
    'rehype-slug': '^6.0.0' # Adds slugs to headings
    'rehype-pretty-code': '^0.14.1' # Syntax highlighting
    'shiki': '^3.13.0' # Syntax highlighting engine
    'reading-time': '^1.5.0' # Estimate reading time
    # Table of content generation
    'remark': '^15.0.1'
  dev:
    'eslint': 9.32.0
    'vitest': 3.2.4
    '@vitejs/plugin-react': '5.0.0'
    'jsdom': '26.1.0'
    '@testing-library/react': '16.3.0'
    '@testing-library/dom': '10.4.1'
    '@testing-library/jest-dom': '6.6.4'
    'vite-tsconfig-paths': '5.1.4'
    'typescript': '5.9.2'
    'typescript-eslint': '8.39.0'
