packages:
  # Turbo only accepts * globs not ** globs
  - "apps/hsp/*"
  - "packages/configs/*"
  - "packages/*"
  - "packages/hsp/*"
catalogs:
  # Pin the versions of the packages in the workspace
  base:
    "@types/node": 22.13.17
  prisma:
    prisma: 6.8.2
  gui:
    react: 19.1.0
    react-dom: 19.1.0
    "@types/react": 19.1.8
    "@types/react-dom": 19.1.6
    next: 15.3.5
  
